- name: Link bashrc configuration
  become: no
  file: state=link src={{role_path}}/files/bashrc/{{item}}.sh dest="{{ lookup('env','HOME') }}/.bashrc.d/{{item}}.sh" force=yes
  with_items:
    - applications
    - maven
    - java

- name: Create applications directory
  become: no
  file: path={{ lookup('env','HOME') }}/applications/ state=directory

- name: Create bin directory
  become: no
  file: path={{ lookup('env','HOME') }}/bin/ state=directory

- include: "{{item}}.yml"
  with_items:
    - fpp
    - maven
    - aurora
    #- idea
    #- pycharm
