endpoint: {{jira.endpoint}}
editor: vim 
user: {{jira.user}}
custom-commands:
  - name: attach alter
    help: Attach an alter script to an issue based on the filename
    args: 
      - name: FILE
        required: true
    script: |-
      FILENAME=$(basename {{args.FILE}})
      ISSUE=$(echo "$FILENAME" | grep -E -o "[A-Z]+-[0-9]+")
      if [ -z "$ISSUE" ] then
          echo "Issue n√£o reconhecida a partir do nome de arquivo $FILENAME"
          exit 2
      fi
      {{jira}} attach create -f $FILENAME $ISSUE {{args.FILE}}
